version: '3.8'

services:
  web:
    container_name: fuel_nginx
    build: docker/nginx
    ports:
      - 9080:80
    volumes:
      - ./src:/var/www/html
    depends_on:
      - app

  app:
    container_name: fuel_php
    build: docker/php
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db
      - cache

  db:
    container_name: fuel_mysql
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sample_app
      MYSQL_USER: sample_app
      MYSQL_PASSWORD: sample_app
    ports:
      - 3306:3306
    volumes:
      - ./docker/db/data:/var/lib/mysql

  cache:
    container_name: fuel_redis
    image: redis:latest
    volumes:
      - ./docker/redis/data:/data
